# -*- coding: utf-8 -*-
"""getting_nearby_api_data.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ypYUDCajCI5U_Uciy398W-pIGQ39Zufs
"""

# Commented out IPython magic to ensure Python compatibility.
#please outcomment this block before running in your environment (I need it in order to run it on GoogleDrive, still figuring this out)
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/My\ Drive/Way\ To\ Go
!pip install GoogleMaps #for GitHub without '!'

import requests
import json
import googlemaps
from urllib.parse import urlencode

#fetching API key from textfile
with open('API_KEY/API_key.txt', 'r') as f:
  api_key = f.read()

'''
#sample call of the Nearby API for testing: can later be deleted
data_type = 'json'
endpoint_nearby_api = f'https://maps.googleapis.com/maps/api/place/nearbysearch/{data_type}'
parameters = {'location': '52.516398873850775, 13.377733528252689', 'radius': 500, 'type': 'tourist_attraction', 'language': 'en', 'key': api_key}
url_parameters = urlencode(parameters)
url = f'{endpoint_nearby_api}?{url_parameters}'
print(url)
'''

#function for collecting information about nearby attractions user might want to pass by
def nearby_attractions(latitude_on_default_route, longitude_on_default_route, radius, attraction_type, data_type = 'json'):
  endpoint_nearby_api = f'https://maps.googleapis.com/maps/api/place/nearbysearch/{data_type}'
  point_on_default_route = str(latitude_on_default_route)+', '+str(longitude_on_default_route)
  parameters = {'location': point_on_default_route, 'radius': radius, 'type': attraction_type, 'language': 'en', 'key': api_key}
  url_parameters = urlencode(parameters)
  url = f'{endpoint_nearby_api}?{url_parameters}'
  data = requests.get(url)
  print(url)
  if data.status_code not in range(200, 299):
    return{}
  return data.json()

#calling nearby_attractions function with some made up input
nearby_attractions(52.50547924295601, 13.439621512395023, 1000, 'cafe')