# -*- coding: utf-8 -*-
"""getting_directions_api_data.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wEhjMNiuWVK4YL3P3SAyq5Q8uhMoKl-p
"""

# Commented out IPython magic to ensure Python compatibility.
#please outcomment this block before running in your environment (I need it in order to run it on GoogleDrive, still figuring this out)
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/My\ Drive/Way\ To\ Go
!pip install GoogleMaps #for GitHub without '!'

import requests
import json
import googlemaps
from urllib.parse import urlencode

#fetching API key from textfile
with open('API_KEY/API_key.txt', 'r') as f:
  api_key = f.read()

'''
#sample call of the Directions API for testing: can later be deleted
data_type = 'json'
endpoint_directions_api = f'https://maps.googleapis.com/maps/api/directions/{data_type}'
parameters = {'origin': 'Berlin Alexanderplatz', 'destination': 'Berlin Zoologischer Garten', 'mode': 'walking', 'language': 'en', 'key': api_key}
url_parameters = urlencode(parameters)
url = f'{endpoint_directions_api}?{url_parameters}'
print(url)
'''

#function for collecting waypoints of the (at this point unmodified) route
def extract_lat_lng(current_loc, desired_dest, data_type = 'json'):
  endpoint_directions_api = f'https://maps.googleapis.com/maps/api/directions/{data_type}'
  parameters = {'origin': current_loc, 'destination': desired_dest, 'mode': 'walking', 'language': 'en', 'key': api_key}
  url_parameters = urlencode(parameters)
  url = f'{endpoint_directions_api}?{url_parameters}'
  data = requests.get(url)
  print(url)
  if data.status_code not in range(200, 299):
    return{}
  return data.json() 

#calling waypoints function with some made up input
extract_lat_lng('Berlin Volkspark Friedrichshain', 'Berlin Potsdamer Platz')